/**
 * This package documentation describes the Captcha implementation in Greenfield Times.
 * 
 * <h2>Implementation</h2>
 * <p>The captcha implementation in Greenfield Times is stateless. It functions by setting a cookie
 * on the target browser with a DES encrypted version of the correct captcha value  on every request
 * to the servlet in charge of generating the images. The cookie is then transported back to the server
 * when a comment POST occurs. Here verification is done by matching the user input with the cookie value.</p>
 *
 * <p>To avoid the situation where an attacker knows a valid captcha/encryption pair, and repeatedly posts
 * with it, each front server employs a burn list. The burn list keeps track of the 1000 latest correctly
 * verified captchas on that front, and automatically flags repeat posts of these captchas as invalid.</p>
 *
 * <p>In a load balanced scheme, this theoretically allows an attacker to succesfully submit <em>N</em> messages
 * with the same captcha pair, where <em>N</em> is the number of fronts. After at most <em>N</em> succesful posts,
 * each server will have the captcha in its burn list.</p>
 * 
 * <p>To further minimize the risk of multiple postings, sticky sessions may be employed, to force a user on to
 * a front. The current implementation avoids this by default, for performance reasons.</p>
 * 
 * <p>Note that the Captcha solution will not work for users which have disabled cookies. A message
 * encouraging the users to enable cookies to be able to comment is displayed instead.</p>
 * 
 * <h2>How the picture is generated</h2>
 * <p>The Captcha picture is generated by the {@link example.captcha.DefaultCaptchaFactory}.
 * This engine supplies a number of default parameters to JCaptcha, which in turn generates the actual image.
 * This can be customized to make the Captcha easier, or harder, to read.</p>
 * 
 * <h2>Disabling Captcha</h2>
 * <p>The Captcha can be both enabled and disabled by configuration of the content <tt>example.CaptchaSettingsConfig</tt>,
 * which may be found under <em>System Department &rarr; Forum Settings &rarr; Captcha Configuration</em>.</p>
 */
package example.captcha;
